bind_addr = "localhost:9000"
log_level = "debug"
files_directory = "/tmp/"
previews_directory = "/tmp/"

database_url = "host=localhost dbname=burst_dev sslmode=disable user=postgres password=docker"
